<?php
/**
 * @var \MaksymZ\RegularCustomer\Block\Product\View\RegularCustomerRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
?>

<div class="actions-toolbar">
    <div class="primary">
        <input type="hidden"
               name="product_id"
               value="<?= $escaper->escapeHtmlAttr((int)$product->getId()) ?>"
        />
        <button type="submit"
                title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                class="action submit primary"
        >
            <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
        </button>
    </div>
</div>

