<?php
/**
 * @var \MaksymZ\RegularCustomer\Block\Product\View\RegularCustomerRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
?>
<div class="dv-campus-personal-discount-request">
    <span><?= $escaper->escapeHtml(__('Loyalty program for Regular Customers')) ?></span>
</div>
