<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<div>
    <ul>
        <li><?= $escaper->escapeHtml(__('Vendor name:')) ?>
            <?= $escaper->escapeHtmlAttr(__($block->getRequest()->getParam('vendorName', 'default'))) ?>
        </li>
        <li><?= $escaper->escapeHtml(__('Module name:')) ?>
            <?= $escaper->escapeHtmlAttr(__($block->getRequest()->getParam('moduleName', 'default'))) ?>
        </li>
    </ul>
</div>
