<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>

<div>
    <ul>
        <li><?= $escaper->escapeHtml(__('Vendor name: %1', $block->getRequest()->getParam('vendorName', 'default'))) ?></li>
        <li><?= $escaper->escapeHtml(__('Module name: %1', $block->getRequest()->getParam('moduleName', 'default'))) ?></li>
    </ul>
</div>
